### ISSUE TITLE
WOW, can you share it?

### ISSUE THREAD

**Issue by x1911** [Domenicobrz/C2-Renderer#1]
It looks fantastic, is there any tutorial or example to show man how to use this?

**Comment by Domenicobrz** [comment]
Hello and thank you for the compliment! You can find examples on how to use
the project by looking at the createScene function, though to be fully
honest there's a much better project called threejs-gpu-pathtracing which
is miles better than this one and it's worth taking a look!
Have fun :)

Il mer 15 feb 2023, 13:46 x1911 ***@***.***> ha scritto:
